#import "___FILEBASENAME___.h"
___COREDATAMANAGEDOBJECTIMPORTEDHEADERS___


@interface ___FILEBASENAMEASIDENTIFIER___ ()

@end


@implementation ___FILEBASENAMEASIDENTIFIER___

___COREDATAPROPERTYIMPLEMENTATIONS___
@end
